In [1]:
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
from scipy.stats import poisson
import statistics as st
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

print(tf.__version__)

2.6.0

In [3]:
upcoming_conmebol = pd.read_csv("/Users/abhijotsingh/Desktop/AtlassianDatathon/INTERCONFED/INPUT/upcoming_interconfed.csv")
conmebol = pd.read_csv("/Users/abhijotsingh/Desktop/AtlassianDatathon/CONMEBOL/INPUTS/conmebol_input.csv")
upcoming_conmebol
# home_xg = conmebol["H_xG"]
# away_xg = conmebol["A_xG"]

,Home,Away,H_rank,A_rank,Rank_diff,Rank_value,Home_GF,Home_GA,Away_GF,Away_GA,H_attack,H_defence,A_attack,A_defence
0,Costa Rica,New Zealand,50,121,-71,-0.1775,1.417461,0.644464,1.350278,2.044167,0.862744,1.037561,1.047137,1.139315
1,Ecuador,Japan,54,28,26,0.0650,2.063880,1.321410,1.740000,0.626667,1.406581,1.229820,1.920715,0.448048
2,New Zealand,Costa Rica,121,50,71,0.1775,0.744069,1.353971,1.148929,1.398690,0.414706,1.050001,1.849729,0.851319
3,Japan,Ecuador,28,54,-26,-0.0650,2.617189,0.897542,0.972879,1.569456,1.871210,0.990760,0.905446,1.069620

In [4]:
# Regression model - Neural network for home_xG, away_xg
home_xg_df = conmebol[['home_score', 'H_attack', 'A_defence']]
away_xg_df = conmebol[['away_score', 'H_defence', 'A_attack']]

# Splitting dataset
train_homexG = home_xg_df.sample(frac=0.8, random_state = 0)
test_homexG = home_xg_df.drop(train_homexG.index)

train_awayxG = away_xg_df.sample(frac=0.8, random_state = 0)
test_awayxG = away_xg_df.drop(train_awayxG.index)

# For home_xG
train_features = train_homexG.copy()
test_features = test_homexG.copy()

train_labels = train_features.pop('home_score')
test_labels = test_features.pop('home_score')

# For away_xG
train_features2 = train_awayxG.copy()
test_features2 = test_awayxG.copy()

train_labels2 = train_features2.pop('away_score')
test_labels2 = test_features2.pop('away_score')

In [5]:
# Pre-processing, home / away
normalizer = preprocessing.Normalization(axis=-1)
normalizer.adapt(np.array(train_features))

normalizer2 = preprocessing.Normalization(axis=-1)
normalizer2.adapt(np.array(train_features2))

# Model functions, home / away
# home
linear_model = tf.keras.Sequential([
    normalizer,
    layers.Dense(units=1)
])
# away
linear_model2 = tf.keras.Sequential([
    normalizer2,
    layers.Dense(units=1)
])

def build_and_compile_model(norm):
  model = keras.Sequential([
      norm,
      layers.Dense(64, activation='relu'),
      layers.Dense(64, activation='relu'),
      layers.Dense(1)
  ])

  model.compile(loss='mean_absolute_error',
                optimizer=tf.keras.optimizers.Adam(0.001))
  return model

# Building model, home / away
dnn_model = build_and_compile_model(normalizer)
dnn_model.summary()

dnn_model2 = build_and_compile_model(normalizer2)
dnn_model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
normalization (Normalization (None, 2)                 5
_________________________________________________________________
dense_2 (Dense)              (None, 64)                192
_________________________________________________________________
dense_3 (Dense)              (None, 64)                4160
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 65
=================================================================
Total params: 4,422
Trainable params: 4,417
Non-trainable params: 5
_________________________________________________________________
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
normalization_1 (Normalizati (None, 2)                 5
_________________________________________________________________
dense_5 (Dense)              (None, 64)                192
_________________________________________________________________
dense_6 (Dense)              (None, 64)                4160
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 65
=================================================================
Total params: 4,422
Trainable params: 4,417
Non-trainable params: 5
_________________________________________________________________

In [6]:
%%time
history = dnn_model.fit(
    train_features, train_labels,
    validation_split=0.2,
    verbose=0, epochs=1000)

# training model home

CPU times: user 25.4 s, sys: 3.45 s, total: 28.8 s
Wall time: 21.6 s

In [7]:
%%time
history = dnn_model2.fit(
    train_features2, train_labels2,
    validation_split=0.2,
    verbose=0, epochs=1000)

# training model away

CPU times: user 25.4 s, sys: 3.48 s, total: 28.9 s
Wall time: 21.8 s

In [8]:
test_results = {}
test_results['dnn_model'] = dnn_model.evaluate(test_features, test_labels, verbose=0)
pd.DataFrame(test_results, index=['Mean absolute error [home_score]']).T

test_results2 = {}
test_results2['dnn_model2'] = dnn_model2.evaluate(test_features2, test_labels2, verbose=0)
pd.DataFrame(test_results2, index=['Mean absolute error [away_score]']).T

            Mean absolute error [away_score]
dnn_model2                          0.852566

In [9]:
# Predicting home_xG and away_xG for upcoming fixtures
home_xg_features = upcoming_conmebol[['H_attack', 'A_defence']]
pred_home_xg = dnn_model.predict(home_xg_features).flatten()
pred_home_xg = [0 if i < 0 else i for i in pred_home_xg]

away_xg_features = upcoming_conmebol[['H_defence', 'A_attack']]
pred_away_xg = dnn_model2.predict(away_xg_features).flatten()
pred_away_xg = [0 if i < 0 else i for i in pred_away_xg]
pred_home_xg

[1.2733268, 0.7481965, 1.8436571, 4.0356774]

In [10]:
# Run the poisson results for the home team
home_outcome = []

for i in range(len(pred_home_xg)):
    expected = pred_home_xg[i]
    poi = poisson.rvs(expected, size=10000)
    # Select most common outcome and append to the poisson outcome list
    common = st.mode(poi)
    home_outcome.append(common)

#home_outcome

In [11]:
# Run the poisson results for the away team
away_outcome = []

for i in range(len(pred_away_xg)):
    expected = pred_away_xg[i]
    poi = poisson.rvs(expected, size=10000)
    # Select most common outcome and append to the poisson outcome list
    common = st.mode(poi)
    away_outcome.append(common)

#away_outcome

In [12]:
upcoming_conmebol["Poisson_H_xG"] = home_outcome
upcoming_conmebol["Poisson_A_xG"] = away_outcome
conmebol_result = upcoming_conmebol[['Home', 'Away', 'Poisson_H_xG', 'Poisson_A_xG']]

result = []
outcomes = ["H_WIN", "DRAW", "A_WIN"]
for i in range(len(away_outcome)):
    if upcoming_conmebol["Poisson_H_xG"][i] > upcoming_conmebol["Poisson_A_xG"][i]:
        result.append(outcomes[0])
    elif upcoming_conmebol["Poisson_H_xG"][i] == upcoming_conmebol["Poisson_A_xG"][i]:
        result.append(outcomes[1])
    else:
        result.append(outcomes[2])

conmebol_result["Results"] = result

H_Points = []
A_Points = []
for i in range(len(away_outcome)):
    if result[i] == "H_WIN":
        H_Points.append(3)
        A_Points.append(0)
    elif result[i] == "DRAW":
        H_Points.append(1)
        A_Points.append(1)
    else:
        H_Points.append(0)
        A_Points.append(3)
       
        
conmebol_result["H_Points"] = H_Points
conmebol_result["A_Points"] = A_Points
conmebol_result

,Home,Away,Poisson_H_xG,Poisson_A_xG,Results,H_Points,A_Points
0,Costa Rica,New Zealand,1,1,DRAW,1,1
1,Ecuador,Japan,0,0,DRAW,1,1
2,New Zealand,Costa Rica,1,0,H_WIN,3,0
3,Japan,Ecuador,4,2,H_WIN,3,0

In [13]:
# Create Points Table
result_table = pd.DataFrame(columns=['Team','GF','GA', 'Points'])
conmebol_home = conmebol_result.groupby("Home")["H_Points"].sum()
conmebol_away = conmebol_result.groupby("Away")["A_Points"].sum()
points = conmebol_home + conmebol_away
H_GF = conmebol_result.groupby("Home")["Poisson_H_xG"].sum()
A_GF = conmebol_result.groupby("Away")["Poisson_A_xG"].sum()
H_GA = conmebol_result.groupby("Home")["Poisson_A_xG"].sum()
A_GA = conmebol_result.groupby("Away")["Poisson_H_xG"].sum()

GF = H_GF + A_GF
GA = H_GA + A_GA

team_list = pd.unique(conmebol_result["Home"])
team_list_sort = sorted(team_list)

result_table["Points"] = points
result_table["GF"] = GF
result_table["GA"] = GA
result_table["Team"] = team_list_sort
result_table

                    Team  GF  GA  Points
Home
Costa Rica    Costa Rica   1   2       1
Ecuador          Ecuador   2   4       1
Japan              Japan   4   2       4
New Zealand  New Zealand   2   1       4

In [15]:
#conmebol_result.to_csv("/Users/abhijotsingh/Desktop/AtlassianDatathon/INTERCONFED/OUTPUT/interconfed_results.csv", index=False)
# result_table.to_csv("/Users/abhijotsingh/Desktop/AtlassianDatathon/CONMEBOL/OUTPUT/conmebol_points_table.csv", index=False)